### ISSUE TITLE
Lab Report 4 Feedback

### ISSUE THREAD

**Issue by Amaar-V** [grantcoz/cse15l-lab-reports#4]
Here is your feedback for Lab Report 4:
 
- [x] Provides link to their markdown-parse repository
- [x] Provides link to the markdown-parse repository they reviewed
 
Snippet 1
- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation
  - the image does not load
- [x] Shows the output of running for the implementation they reviewed
  - the image does not load
- [x] Answers the code change question about their program
 
Snippet 2
- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation
  - the image does not load
- [x] Shows the output of running for the implementation they reviewed
  - the image does not load
- [x] Answers the code change question about their program
 
Snippet 3
- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation
  - the image does not load
- [x] Shows the output of running for the implementation they reviewed
  - the image does not load
- [x] Answers the code change question about their program
 
Additional comments from your grader:
 **Excellent Work**
*Please leave any comments if you have any questions or concerns, thanks!*

Feel free to comment below any questions about the rubric/feedback

**Comment by grantcoz** [comment]
Hello, so when I edited the lab report on vs-code the images would show however for some reason when I updated the report and pushed it to GitHub the image link became PNG instead of png, and apparently, that was the reason why the images were not showing on GitHub pages.
